### ISSUE TITLE
Type of TPU used

### ISSUE THREAD

**Issue by rc14193** [ChrisChrisLoLo/chaskets1#1]
There are different hardness TPUs can you clarify what type and add that to the readme. I'm assuming 95A, but I'm not sure. Is that correct?

**Comment by ChrisChrisLoLo** [comment]
Hey! 95A should work, that's the shore hardness of TPU I used. Even if it varies though, I suspect the experience should be roughly similar in terms of dampening capability and feel. As such, I think any TPU should do the trick, though I can update the readme to list what I used

Hope this helps!
